# Generated by Django 4.2.10 on 2024-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0002_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes_by_students', to='classroom_management.student'),
        ),
    ]
