# Generated by Django 4.2.10 on 2024-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0003_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_session',
            name='students_present',
            field=models.ManyToManyField(blank=True, related_name='students_attendance', to='classroom_management.student'),
        ),
    ]
