# Generated by Django 4.2.10 on 2024-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0004_alter_attendance_session_students_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_session',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
