# Generated by Django 4.2.10 on 2024-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0005_alter_attendance_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_session',
            name='session_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
