# Generated by Django 4.2.10 on 2024-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0006_attendance_session_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_session',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
    ]
