# Generated by Django 4.2.10 on 2024-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0007_alter_attendance_session_session_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='classroom',
            name='course_code',
            field=models.CharField(default=404, max_length=9, unique=True),
        ),
    ]
