# Generated by Django 4.2.10 on 2024-04-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0008_remove_student_semester_classroom_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance_session',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='attendance_session',
            name='session_number',
        ),
    ]
