# Generated by Django 4.2.11 on 2024-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0009_alter_attendance_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encodings',
            field=models.TextField(default='[]'),
        ),
    ]
